version: "3.8"
services:
 postgres:
    image: kartoza/postgis:12.0
    container_name: my-postgres
    ports:
      - "5432:5432"
    networks:
      - testnetwork
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser


networks:
  testnetwork:
volumes:
  postgres:
    driver: local